LCD-51340 Include URL in OpenSearch download failure message

diff --git a/cloud/helm/aws/values.yaml b/cloud/helm/aws/values.yaml
--- a/cloud/helm/aws/values.yaml
+++ b/cloud/helm/aws/values.yaml
@@ -88,7 +88,7 @@ liferay-default:
 
                                 if [ "${http_code}" != "200" ]
                                 then
-                                    echo "Unable to download OpenSearch modules for product version ${product_version}." >&2
+                                    echo "Unable to download OpenSearch modules for product version ${product_version} from ${url}." >&2
 
                                     rm --force --verbose /temp/liferay/deploy/com.liferay.portal.search.opensearch2.${1}.jar
 
